"--------------------------------------------------------------------
" ***this file is auto-generated by the SwitchProject command***
" active project: None (run :SwitchProject ~/path/to/your/project)
"--------------------------------------------------------------------

:source ~/.vim/plugin/vimide/static.functions
