"--------------------------------------------------------------------
" ***this file is auto-generated by the SwitchProject command***
" active project: /Users/mike/.vim/plugin/vimide/samples/python
"--------------------------------------------------------------------

:source ./static.functions
