"--------------------------------------------------------------------
" ***this file is auto-generated by the SwitchProject command***
" active project: /home/tomeowl/.vim/plugin/ide/samples/python
"--------------------------------------------------------------------

:source /home/tomeowl/.vim/plugin/ide/static.functions
nmap <F1> :!make --file /home/tomeowl/.vim/plugin/ide/samples/python/Makefile run <CR><CR>
nmap <F4> :!make --file /home/tomeowl/.vim/plugin/ide/samples/python/Makefile kill <CR><CR>
nmap <F2> :!make --file /home/tomeowl/.vim/plugin/ide/samples/python/Makefile test <CR><CR>
