---
version: 1
disable_existing_loggers: False
formatters:
    simple:
        format: "%(levelname)s:%(name)s:%(message)s"

handlers:
    info_handler:
        class: logging.handlers.RotatingFileHandler
        level: INFO
        filename: log/info.log
        formatter: simple
        maxBytes: 10485760 # 10 MB
        encoding: utf8
    debug_handler:
        class: logging.handlers.RotatingFileHandler
        level: DEBUG
        filename: log/debug.log
        formatter: simple
        maxBytes: 10485760 # 10 MB
        encoding: utf8
    warning_handler:
        class: logging.handlers.RotatingFileHandler
        level: WARNING
        filename: log/warning.log
        formatter: simple
        maxBytes: 10485760 # 10 MB
        encoding: utf8
    error_handler:
        class: logging.handlers.RotatingFileHandler
        level: ERROR
        filename: log/error.log
        formatter: simple
        maxBytes: 10485760 # 10 MB
        encoding: utf8

root:
    level: DEBUG
    handlers:
        - error_handler
        - info_handler
        - debug_handler
        - warning_handler
...
